CREATE TABLE IF NOT EXISTS account (
     ID INT AUTO_INCREMENT,
     USER_ID VARCHAR(255) NOT NULL,
     NAME VARCHAR(100) NOT NULL,
     ENABLED BOOL DEFAULT TRUE,
     PRIMARY KEY (ID),
     CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES user(ID)
);